name: C/C++ CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: ncurses
      run: sudo apt-get install libncurses5-dev
    - name: make
      run: make

